export type InventoryKind =
  | "RING"
  | "LUG"
  | "HARNESS"
  | "STICK"
  | "SIMBAL"
  | "HEAD"
  | "BODY-SNARE"
  | "BODY-TOM"
  | "BODY-BASS"
  | "BODY-GENERAL"
  | "FIN-HPL"
  | "FIN-MIKA"
  | "PIPE"
  | "SPAREPART"
  | "BRACKET"
  | "STRAINER"
  | "STAND"
  | "BELL"
  | "MAHKOTA"
  | "HOLDER"
  | "RIM";

export type InventoryItem = {
  code: string;
  name: string;
  stock: number;
  category: string;
  subCategory?: "SNARE" | "TOM";
  kind?: InventoryKind;
};

export type InventoryItemWithKind = InventoryItem & { kind: InventoryKind };

export const inventoryItems: InventoryItem[] = [
  {
    code: "ACC-GEN-00-STD",
    name: "Stick Snare & Tom  TK",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD10",
    name: "Mata Ayam Biasa",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD11",
    name: "Mahkota Mayoret Besar",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD12",
    name: "Mahkota Mayoret Kecil",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD13",
    name: "Tunjung Mahkota",
    stock: 5,
    category: "Acc",
  },
  { code: "ACC-GEN-00-STD14", name: "Spicer Tom", stock: 5, category: "Acc" },
  {
    code: "ACC-GEN-00-STD15",
    name: "Kempongan Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD16",
    name: "Cantolan Bass",
    stock: 5,
    category: "Acc",
  },
  { code: "ACC-GEN-00-STD17", name: "Pengait Bass", stock: 5, category: "Acc" },
  {
    code: "ACC-GEN-00-STD18",
    name: "Mallet Holder",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD19",
    name: "Pancingan Snare",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD2",
    name: "Stick Snare & Tom SD",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD20",
    name: "Pancingan Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD3",
    name: "Stick Snare & Tom SMP/SMA",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD4",
    name: "Stick Bass Drumband",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD5",
    name: "Stick Tenor TK",
    stock: 5,
    category: "Acc",
  },
  { code: "ACC-GEN-00-STD6", name: "Stick Tenor", stock: 5, category: "Acc" },
  {
    code: "ACC-GEN-00-STD7",
    name: "Strainer Drumband",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD8",
    name: "Kunci Steam Kecil",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-00-STD9",
    name: "Kunci Steam Besar",
    stock: 5,
    category: "Acc",
  },
  { code: "ACC-GEN-01-STD", name: "Claw 1,5mm", stock: 5, category: "Acc" },
  { code: "ACC-GEN-01-STD2", name: "Baut 1cm 6x10", stock: 5, category: "Acc" },
  { code: "ACC-GEN-02-STD", name: "Claw 2mm", stock: 5, category: "Acc" },
  {
    code: "ACC-GEN-03-STD",
    name: "Baut Slebor 3/16'' x 1/2'' (TYPE BM)",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-03-STD2",
    name: "Baut Slebor 3/16'' x 1/2''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-05-STD",
    name: "Baut Snare 5cm @325",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-08-STD",
    name: "Cymbal Silver 8''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-10-STD",
    name: "Baut Bass 10cm @200",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-10-STD2",
    name: "Peer Drumband 10''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-10-STD3",
    name: "Cymbal Silver 10''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-12-STD",
    name: "Baut Bass 12cm @100",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-12-STD2",
    name: "Peer Drumband 12''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-12-STD3",
    name: "Cymbal Silver 12''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-13-STD",
    name: "Peer Drumband 13''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-14-STD",
    name: "Peer Drumband 14''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-14-STD2",
    name: "Cymbal Silver 14''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-14-STD3",
    name: "Cymbal Gold 14''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-16-STD",
    name: "Cymbal Silver 16''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-16-STD2",
    name: "Cymbal Gold 16''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-GEN-18-STD",
    name: "Cymbal Gold 18''",
    stock: 5,
    category: "Acc",
  },
  { code: "ACC-HPL-10-STD", name: "10'' HPL Snare", stock: 5, category: "Acc" },
  { code: "ACC-HPL-12-STD", name: "12'' HPL Snare", stock: 5, category: "Acc" },
  { code: "ACC-HPL-13-STD", name: "13'' HPL Snare", stock: 5, category: "Acc" },
  { code: "ACC-HPL-14-STD", name: "14'' HPL Snare", stock: 5, category: "Acc" },
  {
    code: "ACC-HPL-22-STD",
    name: "T22 6'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-22-STD2",
    name: "T22 8'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-22-STD3",
    name: "T22 10'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD",
    name: "T28 10'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD10",
    name: "T28 20'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD11",
    name: "T28 22'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD12",
    name: "T28 24'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD13",
    name: "T28 26'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD14",
    name: "T28 28'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD2",
    name: "T28 12'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD3",
    name: "T28 13'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD4",
    name: "T28 14'' HPL Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD5",
    name: "T28 12'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD6",
    name: "T28 13'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD7",
    name: "T28 14'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD8",
    name: "T28 16'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-28-STD9",
    name: "T28 18'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD",
    name: "T30 12'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD10",
    name: "T30 28'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD2",
    name: "T30 13'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD3",
    name: "T30 14'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD4",
    name: "T30 16'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD5",
    name: "T30 18'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD6",
    name: "T30 20'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD7",
    name: "T30 22'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD8",
    name: "T30 24'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-30-STD9",
    name: "T30 26'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD",
    name: "T33 12'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD10",
    name: "T33 28'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD2",
    name: "T33 13'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD3",
    name: "T33 14'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD4",
    name: "T33 16'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD5",
    name: "T33 18'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD6",
    name: "T33 20'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD7",
    name: "T33 22'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD8",
    name: "T33 24'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-33-STD9",
    name: "T33 26'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD",
    name: "T35 12'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD10",
    name: "T35 28'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD2",
    name: "T35 13'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD3",
    name: "T35 14'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD4",
    name: "T35 16'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD5",
    name: "T35 18'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD6",
    name: "T35 20'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD7",
    name: "T35 22'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD8",
    name: "T35 24'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HPL-35-STD9",
    name: "T35 26'' HPL Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-00-PRM",
    name: "Mata Ayam HTS Premium",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-00-STD",
    name: "Stick Snare & Tom HTS",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-00-STD2",
    name: "Stick Snare & Tom HTS Lite",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-00-STD3",
    name: "Stick Bass HTS",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-00-STD4",
    name: "Mallet Holder HTS",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-13-STD",
    name: "Strainer Snare HTS 13''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-14-STD",
    name: "Strainer Snare HTS 14''",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-HTS-16-STD",
    name: "Cymbal Gold 16'' HTS",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-10-STD",
    name: "10'' Mika Snare",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-12-STD",
    name: "12'' Mika Snare",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-13-STD",
    name: "13'' Mika Snare",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-14-STD",
    name: "14'' Mika Snare",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-22-STD",
    name: "T22 6'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-22-STD2",
    name: "T22 8'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-22-STD3",
    name: "T22 10'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD",
    name: "T28 10'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD10",
    name: "T28 20'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD11",
    name: "T28 22'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD12",
    name: "T28 24'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD13",
    name: "T28 26'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD14",
    name: "T28 28'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD2",
    name: "T28 12'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD3",
    name: "T28 13'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD4",
    name: "T28 14'' Mika Tom",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD5",
    name: "T28 12'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD6",
    name: "T28 13'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD7",
    name: "T28 14'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD8",
    name: "T28 16'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-28-STD9",
    name: "T28 18'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD",
    name: "T30 12'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD10",
    name: "T30 28'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD2",
    name: "T30 13'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD3",
    name: "T30 14'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD4",
    name: "T30 16'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD5",
    name: "T30 18'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD6",
    name: "T30 20'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD7",
    name: "T30 22'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD8",
    name: "T30 24'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-30-STD9",
    name: "T30 26'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD",
    name: "T33 12'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD10",
    name: "T33 28'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD2",
    name: "T33 13'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD3",
    name: "T33 14'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD4",
    name: "T33 16'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD5",
    name: "T33 18'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD6",
    name: "T33 20'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD7",
    name: "T33 22'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD8",
    name: "T33 24'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-33-STD9",
    name: "T33 26'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD",
    name: "T35 12'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD10",
    name: "T35 28'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD2",
    name: "T35 13'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD3",
    name: "T35 14'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD4",
    name: "T35 16'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD5",
    name: "T35 18'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD6",
    name: "T35 20'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD7",
    name: "T35 22'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD8",
    name: "T35 24'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "ACC-MIKA-35-STD9",
    name: "T35 26'' Mika Bass",
    stock: 5,
    category: "Acc",
  },
  {
    code: "BELL-GEN-00-STD",
    name: "Stick Belira Putih",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD2",
    name: "Stick Belira Warna",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD3",
    name: "Harnest Plat Bell TK",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD4",
    name: "Harnest Plat Bell SD",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD5",
    name: "Harnest Plat Bell SMP/A",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD6",
    name: "Marching Bell/Belira Klasik",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD7",
    name: "Connector Marching Bell",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD8",
    name: "Stand Bass dan Bell TK SD",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-00-STD9",
    name: "Stand Bass dan Bell SMP SMA",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-16-STD",
    name: "Marching Bell 16 Keys",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-27-STD",
    name: "Marching Bell 27 Keys",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-30-STD",
    name: "Marching Bell 30 Keys (Kecil)",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-30-STD2",
    name: "Marching Bell 30 Keys (Besar)",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-32-STD",
    name: "Marching Bell 32 Keys (Kecil)",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BELL-GEN-32-STD2",
    name: "Marching Bell 32 Keys (Besar)",
    stock: 5,
    category: "Bell",
  },
  {
    code: "BODY-GEN-10-STD",
    name: "10'' Body Snare LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-10-STD2",
    name: "10'' Body Snare RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-12-STD",
    name: "12'' Body Snare LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-12-STD2",
    name: "12'' Body Snare RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-13-STD",
    name: "13'' Body Snare LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-13-STD2",
    name: "13'' Body Snare RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-14-STD",
    name: "14'' Body Snare LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-14-STD2",
    name: "14'' Body Snare RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD",
    name: "T22 6'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD2",
    name: "T22 8'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD3",
    name: "T22 10'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD4",
    name: "T22 6'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD5",
    name: "T22 8'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-22-STD6",
    name: "T22 10'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD",
    name: "T28 10'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD10",
    name: "T28 13'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD11",
    name: "T28 14'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD12",
    name: "T28 16'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD13",
    name: "T28 18'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD14",
    name: "T28 20'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD15",
    name: "T28 22'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD16",
    name: "T28 24'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD17",
    name: "T28 26'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD18",
    name: "T28 28'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD19",
    name: "T28 12'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD2",
    name: "T28 12'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD20",
    name: "T28 13'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD21",
    name: "T28 14'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD22",
    name: "T28 16'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD23",
    name: "T28 18'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD24",
    name: "T28 20'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD25",
    name: "T28 22'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD26",
    name: "T28 24'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD27",
    name: "T28 26'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD28",
    name: "T28 28'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD3",
    name: "T28 13'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD4",
    name: "T28 14'' Body Tom LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD5",
    name: "T28 10'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD6",
    name: "T28 12'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD7",
    name: "T28 13'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD8",
    name: "T28 14'' Body Tom RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-28-STD9",
    name: "T28 12'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD",
    name: "T30 12'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD10",
    name: "T30 28'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD11",
    name: "T30 12'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD12",
    name: "T30 13'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD13",
    name: "T30 14'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD14",
    name: "T30 16'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD15",
    name: "T30 18'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD16",
    name: "T30 20'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD17",
    name: "T30 22'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD18",
    name: "T30 24'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD19",
    name: "T30 26'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD2",
    name: "T30 13'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD20",
    name: "T30 28'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD3",
    name: "T30 14'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD4",
    name: "T30 16'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD5",
    name: "T30 18'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD6",
    name: "T30 20'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD7",
    name: "T30 22'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD8",
    name: "T30 24'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-30-STD9",
    name: "T30 26'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD",
    name: "T33 12'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD10",
    name: "T33 28'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD11",
    name: "T33 12'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD12",
    name: "T33 13'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD13",
    name: "T33 14'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD14",
    name: "T33 16'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD15",
    name: "T33 18'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD16",
    name: "T33 20'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD17",
    name: "T33 22'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD18",
    name: "T33 24'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD19",
    name: "T33 26'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD2",
    name: "T33 13'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD20",
    name: "T33 28'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD3",
    name: "T33 14'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD4",
    name: "T33 16'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD5",
    name: "T33 18'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD6",
    name: "T33 20'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD7",
    name: "T33 22'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD8",
    name: "T33 24'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-33-STD9",
    name: "T33 26'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD",
    name: "T35 12'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD10",
    name: "T35 28'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD11",
    name: "T35 12'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD12",
    name: "T35 13'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD13",
    name: "T35 14'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD14",
    name: "T35 16'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD15",
    name: "T35 18'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD16",
    name: "T35 20'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD17",
    name: "T35 22'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD18",
    name: "T35 24'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD19",
    name: "T35 26'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD2",
    name: "T35 13'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD20",
    name: "T35 28'' Body Bass RESIN",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD3",
    name: "T35 14'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD4",
    name: "T35 16'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD5",
    name: "T35 18'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD6",
    name: "T35 20'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD7",
    name: "T35 22'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD8",
    name: "T35 24'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-GEN-35-STD9",
    name: "T35 26'' Body Bass LTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-10-PRM",
    name: "10'' Body Snare HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-10-STD",
    name: "10'' Body Snare HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-10-STD2",
    name: "10'' Body Snare Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-12-PRM",
    name: "12'' Body Snare HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-12-STD",
    name: "12'' Body Snare HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-12-STD2",
    name: "12'' Body Snare Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-13-PRM",
    name: "13'' Body Snare HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-13-STD",
    name: "13'' Body Snare HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-13-STD2",
    name: "13'' Body Snare Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-14-PRM",
    name: "14'' Body Snare HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-14-STD",
    name: "14'' Body Snare HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-14-STD2",
    name: "14'' Body Snare Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-PRM",
    name: "T22 6'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-PRM2",
    name: "T22 8'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-PRM3",
    name: "T22 10'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-STD",
    name: "T22 6'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-STD2",
    name: "T22 8'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-22-STD3",
    name: "T22 10'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM",
    name: "T28 10'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM10",
    name: "T28 20'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM11",
    name: "T28 22'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM12",
    name: "T28 24'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM13",
    name: "T28 26'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM14",
    name: "T28 28'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM2",
    name: "T28 12'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM3",
    name: "T28 13'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM4",
    name: "T28 14'' Body Tom HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM5",
    name: "T28 12'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM6",
    name: "T28 13'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM7",
    name: "T28 14'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM8",
    name: "T28 16'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-PRM9",
    name: "T28 18'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD",
    name: "T28 10'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD10",
    name: "T28 20'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD11",
    name: "T28 22'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD12",
    name: "T28 24'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD13",
    name: "T28 26'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD14",
    name: "T28 28'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD15",
    name: "T28 12'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD16",
    name: "T28 13'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD17",
    name: "T28 14'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD18",
    name: "T28 16'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD19",
    name: "T28 18'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD2",
    name: "T28 12'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD20",
    name: "T28 20'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD21",
    name: "T28 22'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD22",
    name: "T28 24'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD23",
    name: "T28 26'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD24",
    name: "T28 28'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD3",
    name: "T28 13'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD4",
    name: "T28 14'' Body Tom HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD5",
    name: "T28 12'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD6",
    name: "T28 13'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD7",
    name: "T28 14'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD8",
    name: "T28 16'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-28-STD9",
    name: "T28 18'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM",
    name: "T30 12'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM10",
    name: "T30 28'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM2",
    name: "T30 13'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM3",
    name: "T30 14'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM4",
    name: "T30 16'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM5",
    name: "T30 18'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM6",
    name: "T30 20'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM7",
    name: "T30 22'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM8",
    name: "T30 24'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-PRM9",
    name: "T30 26'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD",
    name: "T30 12'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD10",
    name: "T30 28'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD11",
    name: "T30 12'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD12",
    name: "T30 13'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD13",
    name: "T30 14'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD14",
    name: "T30 16'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD15",
    name: "T30 18'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD16",
    name: "T30 20'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD17",
    name: "T30 22'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD18",
    name: "T30 24'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD19",
    name: "T30 26'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD2",
    name: "T30 13'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD20",
    name: "T30 28'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD3",
    name: "T30 14'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD4",
    name: "T30 16'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD5",
    name: "T30 18'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD6",
    name: "T30 20'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD7",
    name: "T30 22'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD8",
    name: "T30 24'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-30-STD9",
    name: "T30 26'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM",
    name: "T33 12'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM10",
    name: "T33 28'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM2",
    name: "T33 13'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM3",
    name: "T33 14'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM4",
    name: "T33 16'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM5",
    name: "T33 18'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM6",
    name: "T33 20'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM7",
    name: "T33 22'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM8",
    name: "T33 24'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-PRM9",
    name: "T33 26'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD",
    name: "T33 12'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD10",
    name: "T33 28'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD11",
    name: "T33 12'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD12",
    name: "T33 13'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD13",
    name: "T33 14'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD14",
    name: "T33 16'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD15",
    name: "T33 18'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD16",
    name: "T33 20'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD17",
    name: "T33 22'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD18",
    name: "T33 24'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD19",
    name: "T33 26'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD2",
    name: "T33 13'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD20",
    name: "T33 28'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD3",
    name: "T33 14'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD4",
    name: "T33 16'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD5",
    name: "T33 18'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD6",
    name: "T33 20'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD7",
    name: "T33 22'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD8",
    name: "T33 24'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-33-STD9",
    name: "T33 26'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM",
    name: "T35 12'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM10",
    name: "T35 28'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM2",
    name: "T35 13'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM3",
    name: "T35 14'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM4",
    name: "T35 16'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM5",
    name: "T35 18'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM6",
    name: "T35 20'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM7",
    name: "T35 22'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM8",
    name: "T35 24'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-PRM9",
    name: "T35 26'' Body Bass HTS Premium",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD",
    name: "T35 12'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD10",
    name: "T35 28'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD11",
    name: "T35 12'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD12",
    name: "T35 13'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD13",
    name: "T35 14'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD14",
    name: "T35 16'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD15",
    name: "T35 18'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD16",
    name: "T35 20'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD17",
    name: "T35 22'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD18",
    name: "T35 24'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD19",
    name: "T35 26'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD2",
    name: "T35 13'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD20",
    name: "T35 28'' Body Bass Semi HTS",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD3",
    name: "T35 14'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD4",
    name: "T35 16'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD5",
    name: "T35 18'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD6",
    name: "T35 20'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD7",
    name: "T35 22'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD8",
    name: "T35 24'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "BODY-HTS-35-STD9",
    name: "T35 26'' Body Bass HTS Ultimate",
    stock: 5,
    category: "Body",
  },
  {
    code: "CONN-GEN-00-STD",
    name: "Connector Tom Drumband TK/SD",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-GEN-00-STD2",
    name: "Connector Tom Drumband SMP/SMA",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-GEN-00-STD3",
    name: "Connector Tom  Drumband Trio",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-GEN-00-STD4",
    name: "Connector L + pipa",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-GEN-00-STD5",
    name: "Sambungan Tom Drumband",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-HTS-00-PRM",
    name: "Connector Tom HTS  Premium",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-HTS-00-STD",
    name: "Connector Snare HTS",
    stock: 5,
    category: "Conn",
  },
  {
    code: "CONN-HTS-00-STD2",
    name: "Connector Tom HTS  Lite",
    stock: 5,
    category: "Conn",
  },
  {
    code: "HARN-GEN-00-BLK",
    name: "Harnest Airframe Pipa Hitam Snare",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-BLK2",
    name: "Harnest Airframe Pipa Hitam Bass",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-CHRCHR",
    name: "Harnest Airframe Plat Chrome Snare",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-CHRCHR2",
    name: "Harnest Airframe Plat Chrome Bass",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD",
    name: "Harnest Plat Snare TK",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD10",
    name: "Harnest Fiber Tom TK",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD11",
    name: "Harnest Fiber Tom SD",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD12",
    name: "Harnest Fiber Tom SMP/A",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD13",
    name: "Crop Harnest",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD2",
    name: "Harnest Plat Snare SD",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD3",
    name: "Harnest Plat Snare SMP/A",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD4",
    name: "Harnest Fiber Snare TK",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD5",
    name: "Harnest Fiber Snare SD",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD6",
    name: "Harnest Fiber Snare SMP/A",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD7",
    name: "Harnest Fiber Bass TK",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD8",
    name: "Harnest Fiber Bass SD",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HARN-GEN-00-STD9",
    name: "Harnest Fiber Bass SMP/A",
    stock: 5,
    category: "Harn",
  },
  {
    code: "HEAD-GEN-06-BLK",
    name: "Head Hitam 6''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-06-STD",
    name: "Head Putih 6''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-06-STD2",
    name: "Head Double Oil 6''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-08-BLK",
    name: "Head Hitam 8''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-08-STD",
    name: "Head Putih 8''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-08-STD2",
    name: "Head Double Oil 8''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-10-BLK",
    name: "Head Hitam 10''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-10-STD",
    name: "Head Putih 10''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-10-STD2",
    name: "Head Bottom 10''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-10-STD3",
    name: "Head Double Oil 10''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-10-STD4",
    name: "Head Kevlar 10''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-12-BLK",
    name: "Head Hitam 12''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-12-STD",
    name: "Head Putih 12''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-12-STD2",
    name: "Head Bottom 12''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-12-STD3",
    name: "Head Double Oil 12''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-12-STD4",
    name: "Head Kevlar 12''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-13-BLK",
    name: "Head Hitam 13''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-13-STD",
    name: "Head Putih 13''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-13-STD2",
    name: "Head Bottom 13''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-13-STD3",
    name: "Head Double Oil 13''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-13-STD4",
    name: "Head Kevlar 13''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-14-BLK",
    name: "Head Hitam 14''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-14-STD",
    name: "Head Putih 14''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-14-STD2",
    name: "Head Bottom 14''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-14-STD3",
    name: "Head Double Oil 14''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-14-STD4",
    name: "Head Kevlar 14''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-16-BLK",
    name: "Head Hitam 16''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-16-STD",
    name: "Head Putih 16''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-18-BLK",
    name: "Head Hitam 18''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-18-STD",
    name: "Head Putih 18''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-20-BLK",
    name: "Head Hitam 20''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-20-STD",
    name: "Head Putih 20''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-22-BLK",
    name: "Head Hitam 22''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-22-STD",
    name: "Head Putih 22''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-24-BLK",
    name: "Head Hitam 24''",
    stock: 5,
    category: "Head",
  },
  {
    code: "HEAD-GEN-24-STD",
    name: "Head Putih 24''",
    stock: 5,
    category: "Head",
  },
  { code: "LUG-HTS-05-STD", name: "Lug 5cm HTS", stock: 5, category: "Lug" },
  {
    code: "LUG-HTS-05-STD2",
    name: "Lug 5cm HTS Lite",
    stock: 5,
    category: "Lug",
  },
  { code: "LUG-HTS-07-STD", name: "Lug 7cm HTS", stock: 5, category: "Lug" },
  { code: "LUG-HTS-13-STD", name: "Lug 13cm HTS", stock: 5, category: "Lug" },
  { code: "LUG-HTS-20-STD", name: "Lug 20cm HTS", stock: 5, category: "Lug" },
  { code: "LUG-HTS-22-STD", name: "Lug 22cm HTS", stock: 5, category: "Lug" },
  { code: "LUG-LT-05-STD", name: "Lug 5cm Lite", stock: 5, category: "Lug" },
  {
    code: "LUG-LT-05-STD2",
    name: "Lug 5cm Lite BU MARDI A",
    stock: 5,
    category: "Lug",
  },
  {
    code: "LUG-LT-05-STD3",
    name: "Lug 5cm Lite BU MARDI B",
    stock: 5,
    category: "Lug",
  },
  { code: "LUG-LT-07-STD", name: "Lug 7cm Lite", stock: 5, category: "Lug" },
  {
    code: "LUG-LT-07-STD2",
    name: "Lug 7cm Lite BU MARDI A",
    stock: 5,
    category: "Lug",
  },
  { code: "LUG-LT-12-STD", name: "Lug 12cm Lite", stock: 5, category: "Lug" },
  { code: "LUG-LT-15-STD", name: "Lug 15cm Lite", stock: 5, category: "Lug" },
  {
    code: "LUG-LT-15-STD2",
    name: "Lug 15cm Lite BU MARDI A",
    stock: 5,
    category: "Lug",
  },
  {
    code: "LUG-LT-15-STD3",
    name: "Lug 15cm Lite BU MARDI B",
    stock: 5,
    category: "Lug",
  },
  { code: "LUG-LT-17-STD", name: "Lug 17cm Lite", stock: 5, category: "Lug" },
  { code: "LUG-LT-20-STD", name: "Lug 20cm Lite", stock: 5, category: "Lug" },
  {
    code: "PACK-BASS-13-39X39X40",
    name: "Bass 13'' (39x39x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-14-41X41X40",
    name: "Bass 14'' (41x41x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-16-46X46X40",
    name: "Bass 16'' (46x46x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-18-51X51X40",
    name: "Bass 18'' (51x51x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-20-54X54X40",
    name: "Bass 20'' (54x54x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-22-59X59X40",
    name: "Bass 22'' (59x59x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BASS-24-64X64X40",
    name: "Bass 24'' (64x64x40)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-BELL-00-71X53X30",
    name: "Marching Bell isi 4 (71x53x30)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-10-30X30X66",
    name: "Snare 10'' isi 4 (30x30x66)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-12-35X35X89",
    name: "Snare 12'' isi 4 (35x35x89)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-13-39X39X100",
    name: "Snare 13'' isi 4 (39x39x100)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-13-39X39X50",
    name: "Snare 13'' isi 2 (39x39x50)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-14-41X41X60",
    name: "Snare 14'' isi 2 (41x41x60)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-GEN-14-41X41X92",
    name: "Snare 14'' isi 3 (41x41x92)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-HARN-00-33X40X83",
    name: "Harnest isi 4 (33x40x83)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-HTS-10-35X35X26",
    name: "Snare 10'' HTS isi 1 (35x35x26)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-HTS-12-40X40X30",
    name: "Snare 12'' HTS isi 1 (40x40x30)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-HTS-13-42X42X33",
    name: "Snare 13'' HTS isi 1 (42x42x33)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-HTS-14-44X44X34",
    name: "Snare 14'' HTS isi 1 (44x44x34)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-MAY-00-125X15X15SD",
    name: "Mayoret + Bendera SD (125x15x15)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-MAY-00-155X15X15SMPA",
    name: "Mayoret + Bendera SMP/A (155x15x15)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-QUAR-00-99X30X45",
    name: "Quartom (99x30x45)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-QUIN-00-122X31X51",
    name: "Quin/Quartom SMA (122x31x51)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PACK-TOM-00-85X30X42",
    name: "Tom Trio isi 1 (85x30x42)",
    stock: 5,
    category: "Pack",
  },
  {
    code: "PIPE-HTS-10-STD",
    name: "Pipa Snare HTS 10cm",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-HTS-10-STD2",
    name: "Pipa Snare HTS 10'' (12,5cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-HTS-12-STD",
    name: "Pipa Snare HTS 12'' (16,5cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-HTS-13-STD",
    name: "Pipa Snare HTS 13'' (19,5cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-HTS-14-STD",
    name: "Pipa Snare HTS 14'' (21,5cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-LT-13-STD",
    name: "Pipa Snare Lite 13'' (19cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "PIPE-LT-14-STD",
    name: "Pipa Snare Lite 14'' (21cm)",
    stock: 5,
    category: "Pipe",
  },
  {
    code: "RING-GEN-01-BLKATAS",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 6) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKATAS10",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 8) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS11",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 8) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS12",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 8) Uk. 14'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS2",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 6) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKATAS3",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKATAS4",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKATAS5",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 14'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKATAS6",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 4) Uk. 6'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS7",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 4) Uk. 8'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS8",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 5) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKATAS9",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 6) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKBAWAH",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 6) Uk. 10'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKBAWAH2",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 6) Uk. 12'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKBAWAH3",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 12'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKBAWAH4",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 13'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKBAWAH5",
    name: "Ring Drumband Hitam Tebal 1,2  (lubang 8) Uk. 14'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-BLKBAWAH6",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 5) Uk. 10'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKBAWAH7",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 8) Uk. 13'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-BLKBAWAH8",
    name: "Ring Drumband Hitam Tebal 1,5  (lubang 8) Uk. 14'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 4) Uk.  6'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "TOM",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS10",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 4) Uk. 8'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS11",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 5) Uk. 8'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS12",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 6) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS13",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 8) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS14",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 6) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS15",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 8) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS16",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 8) Uk. 14'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS2",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 4) Uk.  8'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "TOM",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS3",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 6) Uk.  10'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "TOM",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS4",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 8) Uk.  12'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "TOM",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS5",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 5) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS6",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 6) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS7",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 8) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS8",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 8) Uk. 14'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRATAS9",
    name: "Ring Drumband Chrome Tebal 1,5  (lubang 4) Uk. 6'' Atas",
    stock: 5,
    category: "Ring",
    subCategory: "TOM",
  },
  {
    code: "RING-GEN-01-CHRCHRBAWAH",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 5) Uk. 10'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRBAWAH2",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 6) Uk. 12'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRBAWAH3",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 8) Uk. 13'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-01-CHRCHRBAWAH4",
    name: "Ring Drumband Chrome Tebal 1,2  (lubang 8) Uk. 14'' Bawah",
    stock: 5,
    category: "Ring",
    subCategory: "SNARE",
  },
  {
    code: "RING-GEN-04-CHRCHRATAS",
    name: "Ring Snare Chrome Impor (lubang 4) Uk. 8'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-04-STD",
    name: "Ring Baut Kecil 4x1 @1kg",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-06-CHRCHRATAS",
    name: "Ring Snare Chrome Impor (lubang 6) Uk. 10'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-06-CHRCHRATAS2",
    name: "Ring Snare Chrome Impor (lubang 6) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-06-CHRCHRBAWAH",
    name: "Ring Snare Chrome Impor (lubang 6) Uk. 10'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-06-STD",
    name: "Ring Baut Kecil 6x1 @1kg",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-08-CHRCHRATAS",
    name: "Ring Snare Chrome Impor (lubang 8) Uk. 12'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-08-CHRCHRATAS2",
    name: "Ring Snare Chrome Impor (lubang 8) Uk. 13'' Atas",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-08-CHRCHRBAWAH",
    name: "Ring Snare Chrome Impor (lubang 8) Uk. 12'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-08-CHRCHRBAWAH2",
    name: "Ring Snare Chrome Impor (lubang 8) Uk. 13'' Bawah",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-10-STD",
    name: "Ring Baut Kecil 10x1 @1kg",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-12-STD",
    name: "Ring Bass Drumband Besi 12''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-12-STD2",
    name: "Ring Bass Drumband Kayu 12''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-13-STD",
    name: "Ring Bass Drumband Besi 13''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-13-STD2",
    name: "Ring Bass Drumband Kayu 13''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-14-STD",
    name: "Ring Bass Drumband Besi 14''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-14-STD2",
    name: "Ring Bass Drumband Kayu 14''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-16-STD",
    name: "Ring Bass Drumband Besi 16''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-16-STD2",
    name: "Ring Bass Drumband Kayu 16''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-18-STD",
    name: "Ring Bass Drumband Besi 18''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-18-STD2",
    name: "Ring Bass Drumband Kayu 18''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-20-STD",
    name: "Ring Bass Drumband Besi 20''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-20-STD2",
    name: "Ring Bass Drumband Kayu 20''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-22-STD",
    name: "Ring Bass Drumband Besi 22''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-22-STD2",
    name: "Ring Bass Drumband Kayu 22'",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-24-STD",
    name: "Ring Bass Drumband Besi 24''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-24-STD2",
    name: "Ring Bass Drumband Kayu 24''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-26-STD",
    name: "Ring Bass Drumband Besi 26''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-26-STD2",
    name: "Ring Bass Drumband Kayu 26''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-28-STD",
    name: "Ring Bass Drumband Besi 28''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-GEN-28-STD2",
    name: "Ring Bass Drumband Kayu 28''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-00-BLK",
    name: "Kaki Ring Snare HTS Hitam",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-00-CHRCHR",
    name: "Kaki Ring Snare HTS Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-06-STD",
    name: "Ring Semi HTS 6''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-08-STD",
    name: "Ring Semi HTS 8''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-10-BLK",
    name: "RING HTS  10'' Lite Hitam",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-10-CHRCHR",
    name: "RING HTS 10'' Lite Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-10-CHRCHRPRM",
    name: "RING HTS 10'' Premium Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-10-STD",
    name: "Ring Semi HTS 10''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-12-BLK",
    name: "RING HTS  12'' Lite Hitam",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-12-CHRCHR",
    name: "RING HTS 12'' Lite Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-12-CHRCHRPRM",
    name: "RING HTS 12'' Premium Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-12-STD",
    name: "Ring Semi HTS 12''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-13-BLK",
    name: "RING HTS  13'' Lite Hitam",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-13-CHRCHR",
    name: "RING HTS 13'' Lite Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-13-CHRCHRPRM",
    name: "RING HTS 13'' Premium Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-13-STD",
    name: "Ring Semi HTS 13''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-14-BLK",
    name: "RING HTS  14'' Lite Hitam",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-14-CHRCHR",
    name: "RING HTS 14'' Lite Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-14-CHRCHRPRM",
    name: "RING HTS 14'' Premium Chrome",
    stock: 5,
    category: "Ring",
  },
  {
    code: "RING-HTS-14-STD",
    name: "Ring Semi HTS 14''",
    stock: 5,
    category: "Ring",
  },
  {
    code: "STAND-GEN-00-STD",
    name: "Stand Snare dan Tom",
    stock: 5,
    category: "Stand",
  },
];

// Infer a stable InventoryKind from a code/category combination.
export function inferKind(
  item: Pick<InventoryItem, "code" | "category">
): InventoryKind {
  const prefix = item.code.split("-")[0]?.toUpperCase();
  switch (prefix) {
    case "RING":
      return "RING";
    case "LUG":
      return "LUG";
    case "HAR":
    case "HARNESS":
      return "HARNESS";
    case "STICK":
      return "STICK";
    case "SIMBAL":
    case "CYMBAL":
      return "SIMBAL";
    case "HEAD":
      return "HEAD";
    case "BODY":
      if (item.code.includes("-SNR")) return "BODY-SNARE";
      if (item.code.includes("-TOM")) return "BODY-TOM";
      if (item.code.includes("-BAS")) return "BODY-BASS";
      return "BODY-GENERAL";
    case "FIN":
      if (item.code.includes("-HPL")) return "FIN-HPL";
      if (item.code.includes("-MIKA")) return "FIN-MIKA";
      return "FIN-HPL";
    case "PIPE":
      return "PIPE";
    case "SPAREPART":
    case "ACC":
      return "SPAREPART";
    case "BRACKET":
      return "BRACKET";
    case "STRAINER":
      return "STRAINER";
    case "STAND":
      return "STAND";
    case "BELL":
      return "BELL";
    case "MAHKOTA":
      return "MAHKOTA";
    case "HOLDER":
      return "HOLDER";
    case "RIM":
      return "RIM";
    default: {
      const cat = item.category.toUpperCase();
      if (cat.includes("RING")) return "RING";
      if (cat.includes("HARNESS")) return "HARNESS";
      if (cat.includes("LUG")) return "LUG";
      if (cat.includes("PIPE")) return "PIPE";
      if (cat.includes("STAND")) return "STAND";
      return "SPAREPART";
    }
  }
}

export const inventoryItemsWithKind: InventoryItemWithKind[] =
  inventoryItems.map((item) => ({
    ...item,
    kind: inferKind(item),
  }));
