-- CreateTable
CREATE TABLE "BahanBaku" (
    "code" TEXT NOT NULL,
    "name" TEXT,
    "category" TEXT,
    "kind" TEXT,
    "stock" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "BahanBaku_pkey" PRIMARY KEY ("code")
);

INSERT INTO "BahanBaku" ("code", "name", "category")
VALUES
    ('BBK-0001', 'ALUMUNIUM M', 'Bahan Baku'),
    ('BBK-0002', 'AMPLAS A100', 'Bahan Baku'),
    ('BBK-0003', 'AMPLAS A240', 'Bahan Baku'),
    ('BBK-0004', 'AMPLAS A80', 'Bahan Baku'),
    ('BBK-0005', 'BAUT UK 10, PANJANG 1,5CM', 'Bahan Baku'),
    ('BBK-0006', 'BAUT UK 10, PANJANG 3CM', 'Bahan Baku'),
    ('BBK-0007', 'BAUT UK 10, PANJANG 4CM', 'Bahan Baku'),
    ('BBK-0008', 'BENANG WOLL', 'Bahan Baku'),
    ('BBK-0009', 'BESI 0,77X15/35', 'Bahan Baku'),
    ('BBK-0010', 'BESI 1,15X19/39', 'Bahan Baku'),
    ('BBK-0011', 'BESI L 28/28 A', 'Bahan Baku'),
    ('BBK-0012', 'BESI TEBAL 0,6CM', 'Bahan Baku'),
    ('BBK-0013', 'CAT DANA GLOSS', 'Bahan Baku'),
    ('BBK-0014', 'CAT ISAMU CLEAR', 'Bahan Baku'),
    ('BBK-0015', 'CAT ISAMU HITAM', 'Bahan Baku'),
    ('BBK-0016', 'CAT ISAMU PUTIH', 'Bahan Baku'),
    ('BBK-0017', 'CAT ISAMU SILVER', 'Bahan Baku'),
    ('BBK-0018', 'CAT SUZUKA HIJAU', 'Bahan Baku'),
    ('BBK-0019', 'CAT SUZUKA MERAH', 'Bahan Baku'),
    ('BBK-0020', 'CAT SUZUKA ORANGE', 'Bahan Baku'),
    ('BBK-0021', 'CAT VINOTEX HITAM', 'Bahan Baku'),
    ('BBK-0022', 'CLEAR GLOSSY', 'Bahan Baku'),
    ('BBK-0023', 'DEMPUL IMPRA PROPAN', 'Bahan Baku'),
    ('BBK-0024', 'GLITER BIRU MUDA', 'Bahan Baku'),
    ('BBK-0025', 'GLITER BIRU TUA', 'Bahan Baku'),
    ('BBK-0026', 'GLITER HIJAU', 'Bahan Baku'),
    ('BBK-0027', 'GLITER HITAM SPARKLE', 'Bahan Baku'),
    ('BBK-0028', 'GLITER MERAH', 'Bahan Baku'),
    ('BBK-0029', 'GLITER ORANGE', 'Bahan Baku'),
    ('BBK-0030', 'GLITER SILVER', 'Bahan Baku'),
    ('BBK-0031', 'HPL MOTIF HITAM KRAMIK', 'Bahan Baku'),
    ('BBK-0032', 'HPL MOTIF JATI', 'Bahan Baku'),
    ('BBK-0033', 'HPL PUTIH TULANG', 'Bahan Baku'),
    ('BBK-0034', 'LEM AIBON SUPER', 'Bahan Baku'),
    ('BBK-0035', 'LEM ALTECO', 'Bahan Baku'),
    ('BBK-0036', 'LEM GESTON', 'Bahan Baku'),
    ('BBK-0037', 'LEM PRESTO', 'Bahan Baku'),
    ('BBK-0038', 'LEM RESIN', 'Bahan Baku'),
    ('BBK-0039', 'MAHKOTA', 'Bahan Baku'),
    ('BBK-0040', 'MIKA', 'Bahan Baku'),
    ('BBK-0041', 'PIPA 0,5 INCH', 'Bahan Baku'),
    ('BBK-0042', 'PIPA 1 INCH', 'Bahan Baku'),
    ('BBK-0043', 'PIPA SENAR', 'Bahan Baku'),
    ('BBK-0044', 'PIPA STAINLESS 0,8X3/4ML', 'Bahan Baku'),
    ('BBK-0045', 'PLAT BESI', 'Bahan Baku'),
    ('BBK-0046', 'PLAT SETRIP 30X3ML', 'Bahan Baku'),
    ('BBK-0047', 'REMOVER', 'Bahan Baku'),
    ('BBK-0048', 'TALI MAYORET', 'Bahan Baku'),
    ('BBK-0049', 'TEAKWOOD', 'Bahan Baku'),
    ('BBK-0050', 'THINER', 'Bahan Baku'),
    ('BBK-0051', 'TRIPLEK TEBAL 2,2MM', 'Bahan Baku'),
    ('BBK-0052', 'TRIPLEK TEBAL 3MM', 'Bahan Baku')
ON CONFLICT ("code") DO NOTHING;
